=== vextremera/DAW/Marques/NF4 - Validació de Documents/Proves/exercici5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="escola">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumne" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom"/>
                            <xs:element name="edat">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="3"/>
                                        <xs:maxInclusive value="18"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="notes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nota"  maxOccurs="unbounded">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxInclusive value="10"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nom" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vextremera/DAW/Marques/NF4 - Validació de Documents/Proves/exercici5.xml
<escola xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xsi:noNamespaceSchemaLocation="exercici5.xsd"
           nom="Escola Exemplar">
    <alumne>
        <nom>Anna Pérez</nom>
        <edat>12</edat>
        <notes>
            <nota>8.5</nota>
            <nota>7.2</nota>
            <nota>9.0</nota>
        </notes>
    </alumne>
    <alumne>
        <nom>Joan Martí</nom>
        <edat>16</edat>
        <notes>
            <nota>6.8</nota>
            <nota>5.5</nota>
            <nota>7.1</nota>
        </notes>
    </alumne>
</escola>
