=== vextremera/DAW/Marques/NF4 - Validació de Documents/Proves/exercici3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="productes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producte" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="preu" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vextremera/DAW/Marques/NF4 - Validació de Documents/Proves/exercici3.xml
<?xml version="1.0" encoding="UTF-8"?>
<productes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xsi:noNamespaceSchemaLocation="exercici3.xsd">
    <producte>
        <nom>Poma</nom>
        <preu>1.50</preu>
    </producte>
    <producte>
        <nom>Pl√†tan</nom>
        <preu>0.75</preu>
    </producte>
    <producte>
        <nom>Taronges</nom>
        <preu>2.3055667</preu>
    </producte>
</productes>
