<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE persones [

<!ELEMENT persones  (persona+)>
<!ELEMENT persona   (nif, nom, cognom1, cognom2?)>
<!ELEMENT nif       (#PCDATA)>
<!ELEMENT nom    (#PCDATA)>
<!ELEMENT cognom1 (#PCDATA)>
<!ELEMENT cognom2 (#PCDATA)>

]>

<persones>
    <persona>
        <nif>12345678Z</nif>
        <nom>Victor</nom>
        <cognom1>Extremera</cognom1>
        <cognom2>Moreno</cognom2>
    </persona>
    <persona>
        <nif>87654321A</nif>
        <nom>Pepe</nom>
        <cognom1>Garcia</cognom1>
    </persona>
</persones>