=== vextremera/DAW/Marques/NF4 - Validació de Documents/AC4.1_Victor_Extremera/e3_personaVE.dtd
<!ELEMENT persones  (persona+)>
<!ELEMENT persona   (nif, nom, cognom+, (telefon* | correu*), sexe?)>
<!ELEMENT nif       (#PCDATA)>
<!ELEMENT nom       (#PCDATA)>
<!ELEMENT cognom    (#PCDATA)>
<!ELEMENT telefon   (#PCDATA)>
<!ELEMENT correu    (#PCDATA)>
<!ELEMENT sexe      (#PCDATA)>

=== vextremera/DAW/Marques/NF4 - Validació de Documents/AC4.1_Victor_Extremera/e3_personaVE.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE persones SYSTEM "e3_personaVE.dtd">

<persones>
    <persona id="p1">
        <nif id="Z12345678">12345678Z</nif>
        <nom nom="Victor">Victor</nom>
        <cognom>Extremera</cognom>
        <telefon>666666666</telefon>
        <sexe sexe="home">Home</sexe>
    </persona>
    <persona id="p2">
        <nif id="A87654321">87654321A</nif>
        <nom nom="Pepe">Pepe</nom>
        <cognom>Garcia</cognom>
        <cognom>Martinez</cognom>
        <cognom>Testa</cognom>
        <telefon>66323426</telefon>
        <telefon>623434263</telefon>
    </persona>
    <persona id="p3">
        <nif id="A65352351">65352351A</nif>
        <nom nom="Pere">Pere</nom>
        <cognom>Garcia</cognom>
        <correu>holas@gmail.com</correu>
        <correu>ho2s@lavida.com</correu>
        <correu>h421s@hotmail.com</correu>
        <sexe>No-binari</sexe>
    </persona>
    <persona id="p4">
        <nif id="A51435331">51435331A</nif>
        <nom nom="Raul">Raul</nom>
        <cognom>Pi</cognom>
    </persona>
</persones>
