=== vextremera/DAW/Marques/NF4 - Validació de Documents/AC4.1_Victor_Extremera/e4_classeVE.dtd
<!ELEMENT classe  (alumne+)>
<!ELEMENT alumne   (nif, nom, cognom+)>
<!ELEMENT nif       (#PCDATA)>
<!ELEMENT nom       (#PCDATA)>
<!ELEMENT cognom    (#PCDATA)>

<!ATTLIST nif id ID #REQUIRED>
<!ATTLIST nom nom CDATA #REQUIRED>

=== vextremera/DAW/Marques/NF4 - Validació de Documents/AC4.1_Victor_Extremera/e4_classeVE.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE classe SYSTEM "e4_classeVE.dtd">

<classe>
    <alumne>
        <nif>1832644D</nif>
        <nom>Lewis</nom>
        <cognom>Linkong</cognom>
    </alumne>
    <alumne>
        <nif>1832644D</nif>
        <nom>Lewis</nom>
        <cognom>Linkong</cognom>
        <cognom>Campmayo</cognom>
    </alumne>
    <alumne>
        <nif>1832644D</nif>
        <nom>Lewis</nom>
        <cognom>Linkong</cognom>
        <cognom>Sances</cognom>
        <cognom>Masedo</cognom>
        <cognom>Grass</cognom>
    </alumne>
    <alumne>
        <nif>1832644D</nif>
        <nom>Lewis</nom>
        <cognom>Linkong</cognom>
        <cognom>Ca√±adas</cognom>
        <cognom>Extremera</cognom>
    </alumne>
    <alumne>
        <nif>1832644D</nif>
        <nom>Lewis</nom>
        <cognom>Linkong</cognom>
        <cognom>Fedez</cognom>
        <cognom>Martinez</cognom>
        <cognom>Kindred</cognom>
        <cognom>Perez</cognom>
    </alumne>
</classe>
