=== vextremera/DAW/Marques/NF4 - Validació de Documents/AC4.1_Victor_Extremera/e5_classeVE.dtd
<!ELEMENT classe  (persones)>
<!ELEMENT persones (tutor, alumnes)>
<!ELEMENT tutor   (nif, nom, cognom+, telefon*, correu*)>
<!ELEMENT alumnes  (alumne+)>
<!ELEMENT alumne   (nif, nom, cognom+, telefon*, correu*)>
<!ELEMENT nif       (#PCDATA)>
<!ELEMENT nom       (#PCDATA)>
<!ELEMENT cognom    (#PCDATA)>
<!ELEMENT telefon   (#PCDATA)>
<!ELEMENT correu    (#PCDATA)>

=== vextremera/DAW/Marques/NF4 - Validació de Documents/AC4.1_Victor_Extremera/e5_classeVE.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE classe SYSTEM "e5_classeVE.dtd">

<classe>
    <tutor>
        <persona>
            <nif id="D24145523">24145523D</nif>
            <nom nom="Sr">Sr</nom>
            <cognom>Profe</cognom>
            <telefon>611111111</telefon>
            <correu>tutor@sapalomera.cat</correu>
        </persona>
    </tutor>
    <alumnes>
        <persona>
            <nif id="D1832644">1832644D</nif>
            <nom nom="Lewis">Lewis</nom>
            <cognom>Linkong</cognom>
            <telefon>666666666</telefon>
            <telefon>666666666</telefon>
            <correu>lewis@sapalomera.cat</correu>
            <correu>hlinkongs@sapalomera.cat</correu>
            <correu>l.linkong@hotmail.es</correu>
        </persona>
        <persona>
            <nif id="E9427534">9427534E</nif>
            <nom nom="Lewis">Lewis</nom>
            <cognom>Linkong</cognom>
            <cognom>Campmayo</cognom>
        </persona>
        <persona>
            <nif id="G0384238">0384238G</nif>
            <nom nom="Lewis">Lewis</nom>
            <cognom>Linkong</cognom>
            <cognom>Sances</cognom>
            <cognom>Masedo</cognom>
            <cognom>Grass</cognom>
            <correu>s.grass@sapalomera.cat</correu>
            <correu>masedo@hotmail.es</correu>
        </persona>
        <persona>
            <nif id="V48951145">48951145V</nif>
            <nom nom="Lewis">Lewis</nom>
            <cognom>Linkong</cognom>
            <cognom>Ca√±adas</cognom>
            <cognom>Extremera</cognom>
            <telefon>66413416666</telefon>
            <correu>canadas@sapalomera.cat</correu>
            <correu>extremera@hotmail.es</correu>
        </persona>
        <persona>
            <nif id="U93579851">93579851U</nif>
            <nom nom="Lewis">Lewis</nom>
            <cognom>Linkong</cognom>
            <cognom>Fedez</cognom>
            <cognom>Martinez</cognom>
            <cognom>Kindred</cognom>
            <cognom>Perez</cognom>
            <telefon>642141366</telefon>
            <telefon>6643423566</telefon>
            <telefon>6663623266</telefon>
        </persona>
    </alumnes>
</classe>
